import fs from 'node:fs';
import path from 'node:path';
import { CONFIG } from '../src/lib/store.js';
import { norm, isFbsInstitutionName } from '../src/resolve/schools.js';

const SRC = 'http://universities.hipolabs.com/search?country=United+States';
const CACHE = path.join(process.env.TEMP || '/tmp', 'offerwire-us-unis.json');

const raw = process.argv.includes('--offline') && fs.existsSync(CACHE)
  ? JSON.parse(fs.readFileSync(CACHE, 'utf8'))
  : await (async () => {
    const r = await fetch(SRC, { signal: AbortSignal.timeout(60000) });
    if (!r.ok) throw new Error(`source ${r.status}`);
    const j = await r.json();
    fs.writeFileSync(CACHE, JSON.stringify(j));
    return j;
  })();

const EXTRA = [
  'Oklahoma Panhandle State University',
  'Arkansas State University Mid-South',
  'Arkansas Baptist College',
  'Texas College',
  'Louisiana Christian University',
  'Missouri Baptist University',
  'Ohio Christian University',
  'Michigan Christian College',
  'Florida Memorial University',
  'Georgia Military College',
  'Iowa Central Community College',
  'Kansas Wesleyan University',
  'Nebraska Wesleyan University',
  'Indiana Wesleyan University',
  'Oklahoma Baptist University',
  'Colorado Mesa University',
  'Colorado Christian University',
  'Minnesota State University Mankato',
  'Minnesota State University Moorhead',
  'Washington Adventist University',
  'Virginia University of Lynchburg',
  'Tennessee Wesleyan University',
  'Wisconsin Lutheran College',
  'Texas Lutheran University',
];

const seen = new Set();
const out = [];
for (const name of [...raw.map((r) => r.name), ...EXTRA]) {
  const n = norm(name);
  if (n.split(' ').length < 2 || seen.has(n)) continue;
  if (isFbsInstitutionName(name)) continue;
  seen.add(n);
  out.push(name);
}

out.sort();
const dest = path.join(CONFIG, 'non-fbs.txt');
fs.writeFileSync(dest, `# Non-FBS US colleges. Generated by scripts/build-non-fbs.mjs — do not hand-edit.\n# ${out.length} schools\n${out.join('\n')}\n`);
console.log(`wrote ${dest}: ${out.length} non-FBS institutions`);
