// Rebuild config/non-fbs.txt — the roster of US colleges that are NOT FBS football
// programs. This is what stops "The Colorado School of Mines" resolving to Colorado,
// "Wisconsin Lutheran College" to Wisconsin, or "Alabama State University" to Alabama:
// the wire recognises the OTHER school by name instead of inferring around it.
//
//   node scripts/build-non-fbs.mjs            # refresh from the public source
//   node scripts/build-non-fbs.mjs --offline  # rebuild from a cached download
//
// Source: universities.hipolabs.com (free, no key) — every US degree-granting
// institution, four-year and two-year. Entries that ARE the FBS school (Miami
// University, Ohio University, University of Colorado) are removed by running each
// candidate through the same boundary analyser the resolver uses, so the roster can
// never shadow a real FBS program.
import fs from 'node:fs';
import path from 'node:path';
import { CONFIG } from '../src/lib/store.js';
import { norm, isFbsInstitutionName } from '../src/resolve/schools.js';

const SRC = 'http://universities.hipolabs.com/search?country=United+States';
const CACHE = path.join(process.env.TEMP || '/tmp', 'offerwire-us-unis.json');

const raw = process.argv.includes('--offline') && fs.existsSync(CACHE)
  ? JSON.parse(fs.readFileSync(CACHE, 'utf8'))
  : await (async () => {
    const r = await fetch(SRC, { signal: AbortSignal.timeout(60000) });
    if (!r.ok) throw new Error(`source ${r.status}`);
    const j = await r.json();
    fs.writeFileSync(CACHE, JSON.stringify(j));
    return j;
  })();

// Extra programs the public list misses, all of them schools that share a name with an
// FBS school and have shown up in real offer posts.
const EXTRA = [
  'Oklahoma Panhandle State University',
  'Arkansas State University Mid-South',
  'Arkansas Baptist College',
  'Texas College',
  'Louisiana Christian University',
  'Missouri Baptist University',
  'Ohio Christian University',
  'Michigan Christian College',
  'Florida Memorial University',
  'Georgia Military College',
  'Iowa Central Community College',
  'Kansas Wesleyan University',
  'Nebraska Wesleyan University',
  'Indiana Wesleyan University',
  'Oklahoma Baptist University',
  'Colorado Mesa University',
  'Colorado Christian University',
  'Minnesota State University Mankato',
  'Minnesota State University Moorhead',
  'Washington Adventist University',
  'Virginia University of Lynchburg',
  'Tennessee Wesleyan University',
  'Wisconsin Lutheran College',
  'Texas Lutheran University',
];

const seen = new Set();
const out = [];
for (const name of [...raw.map((r) => r.name), ...EXTRA]) {
  const n = norm(name);
  // Single-token names are never safe to strip on (a lone common word), and the
  // resolver only matches roster entries of two tokens or more anyway.
  if (n.split(' ').length < 2 || seen.has(n)) continue;
  // If our own boundary rule reads this name as an FBS school, it is one — keep it off
  // the roster so it can never blank out a genuine mention.
  if (isFbsInstitutionName(name)) continue;
  seen.add(n);
  out.push(name);
}

out.sort();
const dest = path.join(CONFIG, 'non-fbs.txt');
fs.writeFileSync(dest, `# Non-FBS US colleges. Generated by scripts/build-non-fbs.mjs — do not hand-edit.\n# ${out.length} schools\n${out.join('\n')}\n`);
console.log(`wrote ${dest}: ${out.length} non-FBS institutions`);
